### ISSUE TITLE
Unable to locate package rake-completion

### ISSUE THREAD

**Issue by dialex** [ai/rake-completion#12]
I'm using a rake task to install your library, using the two commands you provide on your Readme. However it's failing to find your package. I'm running the commands as sudo, inside a dockerised Ubuntu image.

```sh
> Installing rake completion tool...

add-apt-repository -y ppa:ubuntu-on-rails/ppa
gpg: keyring `/tmp/tmpfc0xitmp/secring.gpg' created
gpg: keyring `/tmp/tmpfc0xitmp/pubring.gpg' created
gpg: requesting key 81C0BE11 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpfc0xitmp/trustdb.gpg: trustdb created
gpg: key 81C0BE11: public key "Launchpad All you need for Ruby/Rails development on Ubuntu" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

apt-get -y install rake-completion
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package rake-completion
rake aborted!
Command failed with status (100): [apt-get -y install rake-completion...]
```

I double checked with `apt-cache show rake-completion` and your package is really gone.
Can you fix this?

**Comment by ai** [comment]
Sorry, I don’t maintain project anymore :(.

Seems like this PPA doesn’t have `rake-completion` package anymore.

There are 2 options:

1. You can build and upload this version to PPA.
2. You can use manually installation https://github.com/ai/rake-completion#other-unix-like

**Comment by dialex** [comment]
The manual installation failed for me. I executed `wget -O /etc/bash_completion.d/rake https://raw.githubusercontent.com/ai/rake-completion/master/rake` and still no completion. Do I have to restart the shell after?

**Comment by ai** [comment]
You should restart, yeap.

**Comment by dialex** [comment]
I've restarted with `exec bash` and still no auto complete.

**Comment by ai** [comment]
I don’t maintain this package anymore. So debug in your hands :).

**Comment by dialex** [comment]
I understand. I've made a PR to warn users about it. It's only fair ;)
